// <auto-generated />
using System;
using Excursion_GPT.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Excursion_GPT.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("modelid");

                    b.PrimitiveCollection<double[]>("Rotation")
                        .HasColumnType("jsonb")
                        .HasColumnName("rotation");

                    b.HasKey("Id");

                    b.HasIndex("ModelId")
                        .IsUnique();

                    b.ToTable("buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Latitude = 55.751244,
                            Longitude = 37.618423
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Latitude = 55.755825999999999,
                            Longitude = 37.6173
                        });
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("buildingid");

                    b.Property<string>("MinioObjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("minioobjectname");

                    b.PrimitiveCollection<double[]>("Position")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("position");

                    b.PrimitiveCollection<double[]>("Rotation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rotation");

                    b.Property<double>("Scale")
                        .HasColumnType("double precision")
                        .HasColumnName("scale");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("trackid");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("TrackId");

                    b.ToTable("models");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<double[]>("Position")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("position");

                    b.PrimitiveCollection<double[]>("Rotation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rotation");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("trackid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("points");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("tracks");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schoolname");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Login = "admin",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$fIWZeN/DLZtPs9OltDnyc.352duNTb7f3SW5J9ylJHNv8IcI8/U9W",
                            Phone = "+1234567890",
                            Role = "Admin",
                            SchoolName = "Admin Academy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Login = "creator",
                            Name = "Creator User",
                            PasswordHash = "$2a$11$6E0uIsWE1Qp8E9mxyocveuRhUbZ6Vmip9J2UGPe40qKwb1Oe9h/wC",
                            Phone = "+0987654321",
                            Role = "Creator",
                            SchoolName = "Art School"
                        });
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Building", b =>
                {
                    b.HasOne("Excursion_GPT.Domain.Entities.Model", "CustomModel")
                        .WithOne()
                        .HasForeignKey("Excursion_GPT.Domain.Entities.Building", "ModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomModel");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Model", b =>
                {
                    b.HasOne("Excursion_GPT.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Excursion_GPT.Domain.Entities.Track", "Track")
                        .WithMany("Models")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Point", b =>
                {
                    b.HasOne("Excursion_GPT.Domain.Entities.Track", "Track")
                        .WithMany("Points")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Track", b =>
                {
                    b.HasOne("Excursion_GPT.Domain.Entities.User", "Creator")
                        .WithMany("CreatedTracks")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Track", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
