// <auto-generated />
using System;
using System.Collections.Generic;
using Excursion_GPT.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Excursion_GPT.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218105036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("modelid");

                    b.Property<string>("NodesJson")
                        .HasColumnType("text")
                        .HasColumnName("nodes_json");

                    b.PrimitiveCollection<List<double>>("Rotation")
                        .HasColumnType("jsonb")
                        .HasColumnName("rotation");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Z")
                        .HasColumnType("double precision")
                        .HasColumnName("z");

                    b.HasKey("Id");

                    b.HasIndex("ModelId")
                        .IsUnique();

                    b.ToTable("buildings");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("buildingid");

                    b.Property<string>("MinioObjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("minioobjectname");

                    b.PrimitiveCollection<List<double>>("Position")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("position");

                    b.PrimitiveCollection<List<double>>("Rotation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rotation");

                    b.Property<double>("Scale")
                        .HasColumnType("double precision")
                        .HasColumnName("scale");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("trackid");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("TrackId");

                    b.ToTable("models");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.ModelFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("MinioObjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("minio_object_name");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.ToTable("model_files");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.ModelPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<Guid>("PolygonId")
                        .HasColumnType("uuid")
                        .HasColumnName("polygon_id");

                    b.HasKey("Id");

                    b.HasIndex("PolygonId");

                    b.HasIndex("ModelId", "PolygonId")
                        .IsUnique();

                    b.ToTable("model_polygons");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<double>>("Position")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("position");

                    b.PrimitiveCollection<List<double>>("Rotation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rotation");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("trackid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("points");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("tracks");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schoolname");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Building", b =>
                {
                    b.HasOne("Excursion_GPT.Domain.Entities.Model", "CustomModel")
                        .WithOne()
                        .HasForeignKey("Excursion_GPT.Domain.Entities.Building", "ModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomModel");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Model", b =>
                {
                    b.HasOne("Excursion_GPT.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Excursion_GPT.Domain.Entities.Track", "Track")
                        .WithMany("Models")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.ModelPolygon", b =>
                {
                    b.HasOne("Excursion_GPT.Domain.Entities.Model", "Model")
                        .WithMany("ModelPolygons")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Excursion_GPT.Domain.Entities.Building", "Polygon")
                        .WithMany()
                        .HasForeignKey("PolygonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Polygon");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Point", b =>
                {
                    b.HasOne("Excursion_GPT.Domain.Entities.Track", "Track")
                        .WithMany("Points")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Track", b =>
                {
                    b.HasOne("Excursion_GPT.Domain.Entities.User", "Creator")
                        .WithMany("CreatedTracks")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Model", b =>
                {
                    b.Navigation("ModelPolygons");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.Track", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("Excursion_GPT.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
